### ISSUE TITLE
Adding  protobuf as requirements

### ISSUE THREAD

**Issue by userimack** [opentracing-contrib/python-grpc#15]
I have installed the requirements from `examples/requirements.txt` and when I am trying the trivial example, it's failing with the following error 
`Traceback (most recent call last):
  File "trivial_server.py", line 13, in <module>
    import command_line_pb2
  File "/Users/mahendra/python-grpc/examples/trivial/command_line_pb2.py", line 6, in <module>
    from google.protobuf import descriptor as _descriptor
ModuleNotFoundError: No module named 'google' 
`

To resolve this error I had to install protobuf. It will be better if we can add it to our requirements file. 
Thanks

**Comment by carlosalberto** [comment]
Fixed via #16
